__author__ = 'Renato'

SC_ESCAPE       = 0x01
SC_1            = 0x02
SC_2            = 0x03
SC_3            = 0x04
SC_4            = 0x05
SC_5            = 0x06
SC_6            = 0x07
SC_7            = 0x08
SC_8            = 0x09
SC_9            = 0x0A
SC_0            = 0x0B
SC_MINUS        = 0x0C    # - on main keyboard
SC_EQUALS       = 0x0D
SC_BACK         = 0x0E    # backspace
SC_TAB          = 0x0F
SC_Q            = 0x10
SC_W            = 0x11
SC_E            = 0x12
SC_R            = 0x13
SC_T            = 0x14
SC_Y            = 0x15
SC_U            = 0x16
SC_I            = 0x17
SC_O            = 0x18
SC_P            = 0x19
SC_LBRACKET     = 0x1A
SC_RBRACKET     = 0x1B
SC_RETURN       = 0x1C    # Enter on main keyboard
SC_LCONTROL     = 0x1D
SC_A            = 0x1E
SC_S            = 0x1F
SC_D            = 0x20
SC_F            = 0x21
SC_G            = 0x22
SC_H            = 0x23
SC_J            = 0x24
SC_K            = 0x25
SC_L            = 0x26
SC_SEMICOLON    = 0x27
SC_APOSTROPHE   = 0x28
SC_GRAVE        = 0x29    # accent grave
SC_LSHIFT       = 0x2A
SC_BACKSLASH    = 0x2B
SC_Z            = 0x2C
SC_X            = 0x2D
SC_C            = 0x2E
SC_V            = 0x2F
SC_B            = 0x30
SC_N            = 0x31
SC_M            = 0x32
SC_COMMA        = 0x33
SC_PERIOD       = 0x34    # . on main keyboard
SC_SLASH        = 0x35    # / on main keyboard
SC_RSHIFT       = 0x36
SC_MULTIPLY     = 0x37    # * on numeric keypad
SC_LMENU        = 0x38    # left Alt
SC_SPACE        = 0x39
SC_CAPITAL      = 0x3A
SC_F1           = 0x3B
SC_F2           = 0x3C
SC_F3           = 0x3D
SC_F4           = 0x3E
SC_F5           = 0x3F
SC_F6           = 0x40
SC_F7           = 0x41
SC_F8           = 0x42
SC_F9           = 0x43
SC_F10          = 0x44
SC_NUMLOCK      = 0x45
SC_SCROLL       = 0x46    # Scroll Lock
SC_NUMPAD7      = 0x47
SC_NUMPAD8      = 0x48
SC_NUMPAD9      = 0x49
SC_SUBTRACT     = 0x4A    # - on numeric keypad
SC_NUMPAD4      = 0x4B
SC_NUMPAD5      = 0x4C
SC_NUMPAD6      = 0x4D
SC_ADD          = 0x4E    # + on numeric keypad
SC_NUMPAD1      = 0x4F
SC_NUMPAD2      = 0x50
SC_NUMPAD3      = 0x51
SC_NUMPAD0      = 0x52
SC_DECIMAL      = 0x53    # . on numeric keypad

SC_F11          = 0x57
SC_F12          = 0x58

SC_F13          = 0x64    #                     (NEC PC98)
SC_F14          = 0x65    #                     (NEC PC98)
SC_F15          = 0x66    #                     (NEC PC98)

SC_KANA         = 0x70    # (Japanese keyboard)
SC_CONVERT      = 0x79    # (Japanese keyboard)
SC_NOCONVERT    = 0x7B    # (Japanese keyboard)
SC_YEN          = 0x7D    # (Japanese keyboard)
SC_NUMPADEQUALS = 0x8D    # = on numeric keypad (NEC PC98)
SC_CIRCUMFLEX   = 0x90    # (Japanese keyboard)
SC_AT           = 0x91    #                     (NEC PC98)
SC_COLON        = 0x92    #                     (NEC PC98)
SC_UNDERLINE    = 0x93    #                     (NEC PC98)
SC_KANJI        = 0x94    # (Japanese keyboard)
SC_STOP         = 0x95    #                     (NEC PC98)
SC_AX           = 0x96    #                     (Japan AX)
SC_UNLABELED    = 0x97    #                        (J3100)
SC_NUMPADENTER  = 0x9C    # Enter on numeric keypad
SC_RCONTROL     = 0x9D
SC_NUMPADCOMMA  = 0xB3    # , on numeric keypad (NEC PC98)
SC_DIVIDE       = 0xB5    # / on numeric keypad
SC_SYSRQ        = 0xB7
SC_RMENU        = 0xB8    # right Alt
SC_HOME         = 0xC7    # Home on arrow keypad
SC_UP           = 0xC8    # UpArrow on arrow keypad
SC_PRIOR        = 0xC9    # PgUp on arrow keypad
SC_LEFT         = 0xCB    # LeftArrow on arrow keypad
SC_RIGHT        = 0xCD    # RightArrow on arrow keypad
SC_END          = 0xCF    # End on arrow keypad
SC_DOWN         = 0xD0    # DownArrow on arrow keypad
SC_NEXT         = 0xD1    # PgDn on arrow keypad
SC_INSERT       = 0xD2    # Insert on arrow keypad
SC_DELETE       = 0xD3    # Delete on arrow keypad
SC_LWIN         = 0xDB    # Left Windows key
SC_RWIN         = 0xDC    # Right Windows key
SC_APPS         = 0xDD    # AppMenu key